### PR TITLE
Fix routes

### PR DESCRIPTION
**Pull request by I-love-ruby**
@gabalicious @chrisseldo

### CODE REVIEW

**Comment by chrisseldo** [comment]
Seems good to me. Justin, have any comments?

**Comment by gabalicious** [comment]
Yes 2 comments 
1. users_controller.rb:43: syntax error, unexpected end-of-input, expecting keyword_end
2. Also @I-love-ruby Is there a reason you are using edit and update methods for users controller.  shouldn't new and create controller methods should be utilized only?

**Comment by gabalicious** [comment]
Chris I will take over Dogkculs's part.. just spoke to him

**Comment by chrisseldo** [comment]
Okay, sorry I was in the shower!

**Comment by I-love-ruby** [comment]
Yes. I thought user can change email address. It could be unnecessary to do so.
Thanks!

**Comment by gabalicious** [comment]
Ok So I will make a pull request shortly on a different branch.

**Comment by I-love-ruby** [comment]
Cool. Thanks!

**Pull request closed without merging**
